#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConAppLSQLExampleTwo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Day10Db")]
	public partial class ProductsDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public ProductsDataDataContext() : 
				base(global::ConAppLSQLExampleTwo.Properties.Settings.Default.Day10DbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PId;
		
		private string _PName;
		
		private System.Nullable<double> _PPrice;
		
		private System.Nullable<System.DateTime> _PMfDate;
		
		private System.Nullable<System.DateTime> _PExDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIdChanging(int value);
    partial void OnPIdChanged();
    partial void OnPNameChanging(string value);
    partial void OnPNameChanged();
    partial void OnPPriceChanging(System.Nullable<double> value);
    partial void OnPPriceChanged();
    partial void OnPMfDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPMfDateChanged();
    partial void OnPExDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPExDateChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PId
		{
			get
			{
				return this._PId;
			}
			set
			{
				if ((this._PId != value))
				{
					this.OnPIdChanging(value);
					this.SendPropertyChanging();
					this._PId = value;
					this.SendPropertyChanged("PId");
					this.OnPIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PName
		{
			get
			{
				return this._PName;
			}
			set
			{
				if ((this._PName != value))
				{
					this.OnPNameChanging(value);
					this.SendPropertyChanging();
					this._PName = value;
					this.SendPropertyChanged("PName");
					this.OnPNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPrice", DbType="Float")]
		public System.Nullable<double> PPrice
		{
			get
			{
				return this._PPrice;
			}
			set
			{
				if ((this._PPrice != value))
				{
					this.OnPPriceChanging(value);
					this.SendPropertyChanging();
					this._PPrice = value;
					this.SendPropertyChanged("PPrice");
					this.OnPPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMfDate", DbType="Date")]
		public System.Nullable<System.DateTime> PMfDate
		{
			get
			{
				return this._PMfDate;
			}
			set
			{
				if ((this._PMfDate != value))
				{
					this.OnPMfDateChanging(value);
					this.SendPropertyChanging();
					this._PMfDate = value;
					this.SendPropertyChanged("PMfDate");
					this.OnPMfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PExDate", DbType="Date")]
		public System.Nullable<System.DateTime> PExDate
		{
			get
			{
				return this._PExDate;
			}
			set
			{
				if ((this._PExDate != value))
				{
					this.OnPExDateChanging(value);
					this.SendPropertyChanging();
					this._PExDate = value;
					this.SendPropertyChanged("PExDate");
					this.OnPExDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
